## Introduction to Numpy



#### Import numpy

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: C:\Users\Student\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

#### Numpy operations
1.- Create array a with values from 1-5 \
2.- create an array b with values from 6 - 10

In [3]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.arange(6, 11)
b


array([ 6,  7,  8,  9, 10])

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



In [5]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:

transpose = matrix.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
sum_matrix = matrix + transpose
sum_matrix


array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [8]:
product_matrix = np.dot(matrix, transpose)
product_matrix


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [10]:
arr[1]


np.int64(20)

In [11]:
arr[-1]

np.int64(60)

In [12]:
arr[1:4]

array([20, 30, 40])

In [13]:
arr[2:]

array([30, 40, 50, 60])

In [14]:
reshaped_arr = arr.reshape((2, 3))
reshaped_arr

array([[10, 20, 30],
       [40, 50, 60]])

#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


In [15]:

np.random.seed(42)
random_array = np.random.rand(3,3)
random_array


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [16]:
random_array_int = np.random.randint(0,10, size=(2,3))
random_array_int

array([[7, 2, 5],
       [4, 1, 7]], dtype=int32)

#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

In [17]:
dataset = np.random.randint(1,51, size=[5,5])
dataset

array([[44, 30, 38,  2, 21],
       [33, 12, 22, 44, 25],
       [49, 27, 42, 28, 16],
       [15, 47, 44,  3, 37],
       [ 7, 21,  9, 39, 18]], dtype=int32)

In [18]:
dataset[dataset > 25] = 0
dataset

array([[ 0,  0,  0,  2, 21],
       [ 0, 12, 22,  0, 25],
       [ 0,  0,  0,  0, 16],
       [15,  0,  0,  3,  0],
       [ 7, 21,  9,  0, 18]], dtype=int32)

In [19]:
np.mean(dataset)

np.float64(6.84)

In [20]:
np.median(dataset)

np.float64(0.0)

In [21]:
np.std(dataset)

np.float64(8.748394138354763)

In [22]:
np.var(dataset)

np.float64(76.53439999999999)

#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.

In [23]:
A = np.array([[2, 3],[0, 1]])
B = np.array([[1, 2],[4, 0]])

In [24]:
C = np.dot(A, B)
C

array([[14,  4],
       [ 4,  0]])

In [25]:
C = np.dot(A, B)
C

array([[14,  4],
       [ 4,  0]])

In [26]:
determinante = np.linalg.det(C)
determinante

np.float64(-15.999999999999998)

In [27]:
inverse = np.linalg.inv(C)
inverse

array([[ 0.   ,  0.25 ],
       [ 0.25 , -0.875]])